### ISSUE TITLE
Support for 4.11.*?

### ISSUE THREAD

**Issue by spirescreative** [ngdot/contao-changenewsmore#1]
This package is able to be installed in 4.11.* but the feature does not show in the News Redirect Target section. Please advise.

Thank you

**Comment by netSpeedyTV** [comment]
Same with 4.9.20

Text is "Hier können Sie die Standard-Weiterleitung überschreiben." but no Field to put in the Text

**Comment by fritzmg** [comment]
Should be fixed by #2.

**Comment by ngdot** [comment]
Thx @fritzmg
